"""change_name_type_100

Revision ID: e107b614e6d9
Revises: b7993a1f8ef2
Create Date: 2026-02-26 10:15:23.229482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e107b614e6d9'
down_revision: Union[str, None] = 'b7993a1f8ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.execute("COMMENT ON TABLE alembic_version IS 'Alembic version table'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.execute('COMMENT ON TABLE alembic_version IS NULL;')
    # ### end Alembic commands ###
