"""add_notes_to_reservation

Revision ID: b7993a1f8ef2
Revises: 000000000001
Create Date: 2026-02-25 18:38:09.032253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7993a1f8ef2'
down_revision: Union[str, None] = '000000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.create_unique_constraint(None, 'buildings', ['name'])
    op.add_column('reservations', sa.Column('notes', sa.String(length=500), nullable=False))
    op.alter_column('reservations', 'purpose',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'purpose',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('reservations', 'notes')
    op.drop_constraint(None, 'buildings', type_='unique')
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=True)
    # ### end Alembic commands ###
